modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/sekwah41/Naruto-Mod/issues"
license="All rights reserved"
[[mods]]
    modId="narutomod"
    version="${file.jarVersion}"
    displayName="Sekwah41's Naruto mod"
    updateJSONURL="https://www.sekwah.com/modversions/narutomod.json"
    displayURL="http://www.planetminecraft.com/mod/naruto-mod-1750133/"
    authors="Sekwah41"
    description='''
        A mod that adds new items and other features to the game that are from/based on the Naturo manga.
        '''

[[dependencies.narutomod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

# https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
[[dependencies.narutomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
