modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/sekwah41/Naruto-Mod/issues"
license="All rights reserved"
[[mods]]
    modId="narutomod"
    version="${file.jarVersion}"
    displayName="Sekwah41's Naruto mod"
    updateJSONURL="https://www.sekwah.com/modversions/narutomod.json"
    displayURL="http://www.planetminecraft.com/mod/naruto-mod-1750133/"
    authors="Sekwah41"
    logoFile="narutologo.png"
    description='''
A mod that adds new items and other features to the game that are from/based on the Naruto manga.
'''

[[dependencies.narutomod]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

# https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
[[dependencies.narutomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.narutomod]]
    modId="sekclib"
    mandatory=true
    versionRange="[0.2.0,)"
    ordering="NONE"
    side="BOTH"
